version: "3.7"

# Stack de Deploy para Portainer - Sistema de Agendamento Clínica
# Domínio: clinica.123atendi.com.br
# Imagens: 123atendi/clinica-agendamento-backend e frontend

services:
  # Backend Node.js API
  backend:
    image: 123atendi/clinica-agendamento-backend:latest
    networks:
      - minha_rede
    environment:
      # Configurações de ambiente (editáveis no Portainer)
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=d710f46cf17d397b02202514a56f963a3ecc68a87ac560fcedbd64978c910f3c533981eb077a21d4dcd4d1f1e0353abeed998bcf8703b3da6b0f4960b1c9ae9a
      - CORS_ORIGIN=https://clinica.123atendi.com.br
    volumes:
      # Persistência do banco SQLite
      - clinica-db:/app/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.clinica-api.rule=Host(`clinica.123atendi.com.br`) && PathPrefix(`/api`)
        - traefik.http.routers.clinica-api.entrypoints=web,websecure
        - traefik.http.routers.clinica-api.priority=10
        - traefik.http.services.clinica-api.loadbalancer.server.port=3001
        - traefik.http.routers.clinica-api.service=clinica-api
        - traefik.http.routers.clinica-api.tls.certresolver=letsencryptresolver

  # Frontend React
  frontend:
    image: 123atendi/clinica-agendamento-frontend:latest
    networks:
      - minha_rede
    environment:
      # URL da API (editável no Portainer)
      - REACT_APP_API_URL=https://clinica.123atendi.com.br/api
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.clinica-frontend.rule=Host(`clinica.123atendi.com.br`)
        - traefik.http.routers.clinica-frontend.entrypoints=web,websecure
        - traefik.http.routers.clinica-frontend.priority=1
        - traefik.http.services.clinica-frontend.loadbalancer.server.port=80
        - traefik.http.routers.clinica-frontend.service=clinica-frontend
        - traefik.http.routers.clinica-frontend.tls.certresolver=letsencryptresolver

networks:
  minha_rede:
    external: true
    name: minha_rede

volumes:
  # Volume para persistência do banco de dados SQLite
  clinica-db:
    external: false
