name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    name: Build Backend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            123atendi/clinica-agendamento-backend:latest
            123atendi/clinica-agendamento-backend:${{ github.sha }}
          cache-from: type=registry,ref=123atendi/clinica-agendamento-backend:buildcache
          cache-to: type=registry,ref=123atendi/clinica-agendamento-backend:buildcache,mode=max

  build-frontend:
    name: Build Frontend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            123atendi/clinica-agendamento-frontend:latest
            123atendi/clinica-agendamento-frontend:${{ github.sha }}
          cache-from: type=registry,ref=123atendi/clinica-agendamento-frontend:buildcache
          cache-to: type=registry,ref=123atendi/clinica-agendamento-frontend:buildcache,mode=max
